### ISSUE TITLE
v1.0.0 instead of v0.5.4

### ISSUE THREAD

**Issue by MGlolenstine** [baptistecdr/rarbg_api#3]
I'm sorry to bring this up, but wouldn't an API change like the async one "deserve" to be a minor version bump in itself?
That's just according to [semver](https://semver.org/).

# EDIT
Actually, according to semver, this would be a *major* version bump, as it introduces backwards-incompatible API.

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

**Comment by baptistecdr** [comment]
Indeed, I just of think that 10 minutes ago...
