### ISSUE TITLE
Endpoint down

### ISSUE THREAD

**Issue by 89z** [baptistecdr/rarbg_api#4]
~~~
PS C:\> curl.exe -I torrentapi.org
HTTP/1.1 403 Forbidden
~~~

https://github.com/baptistecdr/rarbg_api/blob/5454eb74a4824084aca8e37b12104279e1073a88/src/lib.rs#L35

**Comment by baptistecdr** [comment]
Hello,

The endpoint is not dead:
```sh
curl "https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=github_test"
```
```json
{"token":"v7qd3uh8je"}
```

It's normal that you get 403 Forbidden when you give 0 params.

Sincerely,
baptistecdr

**Comment by 89z** [comment]
Need to reopen

~~~
PS C:\> curl.exe 'https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=github_test'
<html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
~~~

**Comment by baptistecdr** [comment]
It seems that it works again.

**Comment by 89z** [comment]
This is interesting. Supposedly, the token is only good for 15 minutes:

https://github.com/baptistecdr/rarbg_api/blob/5454eb74a4824084aca8e37b12104279e1073a88/src/token.rs#L88-L101

but your same token from 3 days ago still works:

~~~
PS C:\> curl.exe -v 'torrentapi.org/pubapi_v2.php?app_id=1&search_string=2020&token=v7qd3uh8je'
*   Trying 172.67.138.171:80...
* Connected to torrentapi.org (172.67.138.171) port 80 (#0)
> GET /pubapi_v2.php?app_id=1&search_string=2020&token=v7qd3uh8je HTTP/1.1
> Host: torrentapi.org
> User-Agent: curl/7.70.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 01 Jun 2021 00:10:43 GMT
~~~

**Comment by baptistecdr** [comment]
Yeah they don't invalidate the token after 15 minutes, but I followed the API (https://webcache.googleusercontent.com/search?q=cache:gCY5Kdzz6PIJ:https://torrentapi.org/apidocs_v2.txt) so If some day they realize their mistake, no change will be needed.
